config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'names#index'
  resources :names
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/name.rb
class Name < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/names_controller.rb
class NamesController < ApplicationController
  def index
    @names = Name.all

  end

  def new
    @name = Name.new
  end

  def create
    Name.create(name_params)
    redirect_to root_path
  end

  def show
    @name = Name.find(params[:id])
  end

  private

  def name_params
    params.require(:name).permit(:name, :state, :position)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/names_helper.rb
module NamesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Potus</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

    <%= link_to 'US Presidents', root_path, class: 'navbar-brand' %>

<div class="collapse navbar-collapse" id="navbarTogglerDemo02">
<ul class="navbar-nav mr-auto mt-2 mt-md-0">
  <li class="nav-item">
    <%= link_to new_name_path, class: 'nav-link' do %>
    <i class="fa fa-plus-circle"></i>Enter President Information
    <% end %>
  </li>
</ul>
</div>
</nav>
    <%= yield %>
  </body>
</html>

app/views/names/index.html.erb
<%= image_tag 'potus.jpg', class: 'img-fluid' %>
<br />
<br />
<h1>US Presidents in chronological order by state</h1>
<br />
<% @names.each do |name| %>
  <div class="booyah-box col-10 offset-1">
  <h2><%= name.position %>. <%= name.name %>, <%= name.state %></h2><br />
  </div>

  <hr />
<% end %>

app/views/names/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Enter Presidential Information</h1>
  <%= simple_form_for @name do |f| %>
    <%= f.input :name %>
    <%= f.input :state %>
    <%= f.input :position %>
    <br />
    <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/names/show.html.erb
<h1><%= @name.name %></h1>